### ISSUE TITLE
Double Linked List

### ISSUE THREAD

**Issue by sahilrider** [sahilrider/DS_ALGO#4]
Add following function:
- [ ] Deletion at any position
- [ ] Display in reverse order
- [ ] Sorting

**Comment by sheikhazhanmohammed** [comment]
Can I give it a try?

**Comment by applauncher19** [comment]
I am doing it in C

**Comment by SuranjanDaw** [comment]
Doing it in C

**Comment by sheikhazhanmohammed** [comment]
Will love to help, just wanted to know if it is for Hacktoberfest 2019
